### ISSUE TITLE
No JS / CSS

### ISSUE THREAD

**Issue by stirfriedpenguin** [marbindrakon/eve-wspace#121]
On my installation everything works except for the CSS / JS. (Ubuntu 12.04, 1GB RAM)

On loading the webpage, the error console fills up with a  bunch of 404's (Files cannot be found)

The command to fill /home/maptool/static with the files succeeded (config isn't the problem)

**Comment by Zumochi** [comment]
Are you using the built-in development server (./manage.py runserver 0.0.0.0:8000) or a webserver (nginx or apache2)?

Problem here is most likely that you are using the development server, or that you are using a webserver but haven't configured a location for the static files.

**Comment by stirfriedpenguin** [comment]
Correct. I'm using the development server. What would I have to do to get it to process the CSS/JS files.

**Comment by marbindrakon** [comment]
Add --insecure to the runserver command to get it to serve static content.
