### ISSUE TITLE
New Small Shattered Wormhole Type ID Missing

### ISSUE THREAD

**Issue by Siernan** [marbindrakon/eve-wspace#122]
The type ID "A009" seems to be a dynamic connection from w-space to a small shattered wormhole.  I've personally documented it connecting C1, C2, C4, C5, and C6 wormholes to a small shattered wormhole on separate occasions.  Just to make sure I'm not being ambiguous, if you're in w-space and you see an A009, it connects to a small shattered hole, regardless of what class you're currently in.

**Comment by marbindrakon** [comment]
Thanks for the report

**Comment by Maarten28** [comment]
It is already available through the fixtures, however your local version needs to be the same as the one on github. Furthermore a reload of the fixture is nescessary.
