### ISSUE TITLE
Added various features: map scaling, wh effects, pilot names under nodes, system details in one view rather than separate tabs, coloured sigs

### ISSUE THREAD

**Issue by proycon** [marbindrakon/eve-wspace#123]
Thanks for the awesome tool and making it open source!! I took the liberty of adapting it for our corp. Aside from some restyling, I added some features you and others may find useful and may want to merge back in the main branch. Here's a [screenshot](http://download.anaproy.nl/evewhmapper.png). 

My fork is [here](http://github.com/proycon/eve-wspace).

**Comment by marbindrakon** [comment]
Holy crap. That is great work. I'd like to merge in at least 90% of that (I need to see how the pilot list works with 20+ users in a system.) 

What bug were you encountering that was requiring multiple clicks? I haven't seen any behavior like that.

**Comment by proycon** [comment]
Thanks. I think the mutiple clicks were related to the tooltip being to close to the mousecursor, and the IGB being too slow, so people clicked the tooltip rather than the node, I tried forwarding the click from the tooltip to the system node, but simply changing the offset to be a bit further fixed it already.

I now also added an extra style feature which we dubbed "zen" mode, a counterweight to the vibrant default colours, enabled by a toggle button at the top. Here's an extra [screenshot](http://download.anaproy.nl/evewhmapper2.png) .

**Comment by proycon** [comment]
About the pilot list, I changed it to a horizonal list, with the first 6 chars of the name if there are multiple people, if the list gets too long, it'll just name a few (4 at most) and then say something like +12.

**Comment by marbindrakon** [comment]
Awesome. If you want, send a PR with all of the stuff you want to contribute upstream.

**Comment by proycon** [comment]
Done, it contains everything, you may prefer to cherry-pick a bit though.

**Comment by marbindrakon** [comment]
Merged
