### ISSUE TITLE
Group permissions not available through admin interface

### ISSUE THREAD

**Issue by acdervis** [marbindrakon/eve-wspace#125]
Certain group permissions such as edit POS, delete POS, use the alerts system aren't grantable through the admin interface, requiring manual DB editing or going through the python shell.

**Comment by Zumochi** [comment]
Yup. If you want I can get you the django shell commands needed to set those permissions.
Because I have no idea how to implement those functions, sadly.

**Comment by acdervis** [comment]
I edited the table with SQL queries before I posted this, posted the issue so any willing developer could take it on. I don't have the know-how about permission/admin page stuff either. I had to scratch my head a bit to understand what was wrong.

**Comment by Maarten28** [comment]
Pull request #135 should take care of this :).

**Comment by Zumochi** [comment]
This can be closed as d9a59c7 took care of it.

**Comment by acdervis** [comment]
@Maarten28 <3
