### ISSUE TITLE
[Comment to proycon-merge]

### ISSUE THREAD

**Issue by neosilver-gk** [marbindrakon/eve-wspace#126]
Looks nice.

I would prefer to leave the tabs for sig, pilot and pos. It is easier to read and work with in a small IGB. 
Also I would like to have the Bulk import form below the sig's.

Otherwise a successful change.

**Comment by Nitesedge** [comment]
Looks good and zen mode rocks.

Thoughts:
- Starbase Details should be a separate page entirely. This info isn't needed as often, some systems have many POSes, page load time and page length both push this item into a separate page accessible from the 
- Red occupied/towers box on system details should default to max of ~10 lines and have a more link to expand if it exceeds 10 lines.
- Move bulk import below sigs as suggested

**Comment by proycon** [comment]
Regarding the tabs versus pages, I think it's probably best to make it user-configurable, as one style simply won't suit all..

**Comment by marbindrakon** [comment]
I merged the big PR in tonight with changes to make map settings configurable on a per-user and global-default basis.

@proycon Let me know when you want me to merge in your changes from this issue or make another PR for it. Thanks for contributing your hard work to the project.

**Comment by proycon** [comment]
Thanks for the merge! I'll do another pull request with the newest features (map overlap, rudimentary pos db view) soon

**Comment by neosilver-gk** [comment]
I've tested the new merge (as I could) and i'm pleased with the new look.

THX
