### ISSUE TITLE
new install, UI is screwed up

### ISSUE THREAD

**Issue by shadowandlight** [marbindrakon/eve-wspace#136]
http://192.99.69.92:800/account/login/?next=/

any ideas what was missed?

**Comment by Maarten28** [comment]
Did you google something like "static files forbidden django" + your server type (apache/nginx)?

If I look at firebug I see the following for all your static files: http://i.imgur.com/2uFOO2E.png

**Comment by Zumochi** [comment]
You need to configure your webserver to point to the mapper's static folder when going to /static

For Apache this would be `Alias /static /home/maptool/static`
For Nginx:
    location /static {
        alias /home/maptool/static;
    }

**Comment by Zumochi** [comment]
@shadowandlight can this be closed or?

**Comment by marbindrakon** [comment]
Closing due to lack of response. Please re-open the issue if you are still having problems.
