### ISSUE TITLE
jQuery: Empty string passed to getElementById() in Firefox

### ISSUE THREAD

**Issue by Zumochi** [marbindrakon/eve-wspace#143]
Oddly enough, this only happens in Firefox. It happens somewhere in the jQuery library. I tried updating it but it didn't fix the issue.

What this problem causes is that wormhole connections won't show up (except for EOL connections, for some reason).
System borders don't show up either (unless clicked on).

Clicking on the map, systems, connections etc. all result in this warning.

**Comment by Maarten28** [comment]
Not having this issue here in FF, is it a cache problem?

**Comment by Zumochi** [comment]
Hmm maybe it's just FF developer edition? Would be weird but could be...

**Comment by marbindrakon** [comment]
What SHA are you seeing this in?

**Comment by Zumochi** [comment]
This is with the latest commit from the develop branch, commit hash 61896ebe3a1318d1ed00c8f3deae1304b58f0a85
Using Firefox Development Edition 38.0a2.
Fresh install.

**Comment by marbindrakon** [comment]
I was able to reproduce this issue in Firefox Developer Edition, but not the regular version.

**Comment by Zumochi** [comment]
Closing as it's related to #149.
