### ISSUE TITLE
Ajax requests for map updates throw time-related error.

### ISSUE THREAD

**Issue by acdervis** [marbindrakon/eve-wspace#148]
```
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)

  File "/home/evewspace/eve-wspace/evewspace/Map/views.py", line 47, in _view
    return view_func(request, map_id, *args, **kwargs)

  File "/home/evewspace/eve-wspace/evewspace/Map/views.py", line 89, in map_checkin
    load_time = datetime.strptime(time_string, "%Y-%m-%d %H:%M:%S.%f")

  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))

ValueError: time data 'null' does not match format '%Y-%m-%d %H:%M:%S.%f'
```

I get this error reported multiple times a day. It's confusing me because most requests go perfectly fine but I get a bunch of these. (around 100 a day, based on activity) It doesn't cause a significant problem for users since their clients just make a new request. It's been going on for ages but I just kept ignoring it since it caused no major issues so it wasn't introduced in a recent patch.

I can provide additional information about the requests throwing the error if desired.

**Comment by marbindrakon** [comment]
Do you notice this behavior from any particular kind of browser?

**Comment by acdervis** [comment]
All types, seems like it mostly happens on the first load because refresh isn't called before update.

We did a quick hack, resolving bulk of the issue for now. At first we thought it was a race condition but it seems it's just standard behavior for refresh to be called every 15s without an initial call.

Here's the code, all under Map/static/js/map_functions.js
```
$(document).ready(function () {
#stuff
RefreshMap()
});
```
and
```
function doMapAjaxCheckin() {
    if(!loadtime) return; #added this line
    var currentPath = "update/";
    $.ajax({
        type: "POST",
        url: currentPath,
        data: {"loadtime": loadtime, "silent": silentSystem, 'kspace': kspaceIGBMapping},
        success: processAjax
    });
}
```

**Comment by Maarten28** [comment]
I'd suggest you start doing pull requests for the code you are writing, if it's not the way Marbin wants it, he can always edit it from there or turn it down. :)

**Comment by acdervis** [comment]
I did, but I failed at doing the git stuff so I gave up trying to fix my messy repo for two lines of code. :<

**Comment by marbindrakon** [comment]
RefreshMap is already called on ready via the scale() function. I will add the checkin bypass though to prevent clients from calling back with invalid loadtime.
