### ISSUE TITLE
stroke-dasharray="0"

### ISSUE THREAD

**Issue by andrewd18** [marbindrakon/eve-wspace#149]
Logged into the SSC mapper tonight (2015-03-31) and found only some of the lines on the map were displayed. According to the DOM, the lines are there, but their stroke-dasharray size is zero. Manually changing it to "9,3" makes the line appear. See screenshot.

https://i.imgur.com/Gz0I2mI.png

**Comment by Zumochi** [comment]
Is this in all browsers or only Firefox? If only Firefox it might be related to #143

**Comment by Maarten28** [comment]
I've tested it in Chrome and FF (both stable), and it only occurs in FF.

**Comment by Zumochi** [comment]
Might be worth reporting that to Mozilla. What version of Firefox are you two using? I'm on 38.0a2.

**Comment by Maarten28** [comment]
37.0 here.

**Comment by marbindrakon** [comment]
There is an issue reported upstream in RaphaelJS regarding this:

https://github.com/DmitryBaranovskiy/raphael/issues/946
