### ISSUE TITLE
[Bug] Empty Scalingfactor

### ISSUE THREAD

**Issue by Zumochi** [marbindrakon/eve-wspace#151]
User gets empty scaling factor if value not explicitly set in admin panel or by user setting.

Steps to reproduce:

* Have a user without personal scaling factor settings
* Go to Settings -> Map Admin -> Display Settings and save display settings without changing any value
* Open a map
* See empty scaling factor value resulting in a unrenderable map.

When the admin sets the value once, the issue is fixed. But still it'd be nice not to have to do that :smile: 

Let me know if the linked PR solves it in the right way or not.

**Comment by marbindrakon** [comment]
Did you run manage.py defaultsettings Map when you upgraded?

**Comment by Zumochi** [comment]
@marbindrakon yes. The problem comes back every time I either do defaultsettings or go to the settings page and save without touching the slider.
