### ISSUE TITLE
Editing admin password in mysql?

### ISSUE THREAD

**Issue by shadowandlight** [marbindrakon/eve-wspace#156]
Is there a way to edit the admin account password in mysql?

**Comment by marbindrakon** [comment]
If you can generate a supported hash, you can edit the account_ewsuser table, but I would recommend editing it through Python so that the proper hash algorithms are used.

If you do edit it in the databse, Django will upgrade the hash to the strongest supported on next login.

**Comment by marbindrakon** [comment]
You can also run manage.py changepassword <username>
