### ISSUE TITLE
[Bug] Firefox 37 not showing system effects

### ISSUE THREAD

**Issue by Maarten28** [marbindrakon/eve-wspace#157]
The ring around a system showing a system effect is not shown in Firefox 37.0.1 anymore. The difference can be seen in the screenshot below: 

![3rvdaly](https://cloud.githubusercontent.com/assets/3999006/7217675/7f7a05e8-e63c-11e4-9f74-2acf72e259a0.png)

Left is FF, right is Chrome (same map). When it is a shattered WH it does show the (dotted) color around it correctly.

**Comment by nyrocron** [comment]
Works in FF 36, stopped working in 37

**Comment by nyrocron** [comment]
This fixes it for me: https://github.com/nyrocron/eve-wspace/commit/ebf7a8da16f7d47a8776626918748fb8815bfa31
