### ISSUE TITLE
[Bug] POS Edit functionality not working

### ISSUE THREAD

**Issue by Maarten28** [marbindrakon/eve-wspace#163]
500 Internal server error when clicking on the pencil on the SSC instance (probably the develop branch), have not been able to reproduce it on my local version which is a few commits behind .

**Comment by Zumochi** [comment]
I have this problem sometimes when *adding* a POS, never when editing (then again I rarely edit POS info). It's usually resolved when I run D-scan and copy it over again. Otherwise when I check the logs, I don't see anything recognizable related to this.

**Comment by kubiq** [comment]
Adding pos also doesn't work for me, Error 500: "Oops, something broke." , post data: https://gist.github.com/kubiq/708483247a7a4d4a2625
