### ISSUE TITLE
Add instruction for importing SDE for postgresql.

### ISSUE THREAD

**Issue by tyler274** [marbindrakon/eve-wspace#179]
The docs only include mention for mysql, a conversion script might be in order to convert the mysql sql to postgresql.

**Comment by Zumochi** [comment]
Granted, I haven't ever used PgSQL, but Fuzzworks has a dump for that as well (e.g. https://www.fuzzwork.co.uk/dump/postgres-latest.dmp.bz2). No need to convert anything.

The steps, however, are very similar.

Assuming you already have a database:

`psql name_of_database < postgres-latest.dmp`

**Comment by tyler274** [comment]
thanks I missed that.
