### ISSUE TITLE
"I'm here" no longer seems to work in OOG browsers

### ISSUE THREAD

**Issue by Zumochi** [marbindrakon/eve-wspace#180]
In the latest version, clicking "I'm here" doesn't seem to do anything. It sends the request as expected but the pilot list is not updated.

Previous version tested where the function still works is a rather old one though: 9edc2723b3464a4e88b05d6d55bcf60da609e230

EDIT: okay there may be another problem involved. Can't seem to be able to automatically add systems and it doesn't recognize players either, both using the in-game browser.

**Comment by marbindrakon** [comment]
Can you make sure memcached is running and try clearing the cache with the following:

`
from django.core.cache import cache
cache.clear()
`

**Comment by Zumochi** [comment]
That simple huh :grimacing: 

Forgot to explicitly enable memcached, BSD and all :smile:
